apiVersion: apps/v1
kind: Deployment
metadata:
  name:  MindBox_webapp
  namespace: test
  labels:
    app:  MindBox_webapp
spec:
  selector:
    matchLabels:
      app: MindBox_webapp
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  MindBox_webapp
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  MindBox_webapp
        image:  MindBox_webapp:latest
        resources:
          requests:
            cpu: 100m                   # Из условия
            memory: 128Mi               # Из условия
          limits:
            cpu: 5                      # т.к приложение потребляет больше процессорного времени на старте
            memory: 150Mi               # Лимит больше на всяк
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 12       # С запасом по времени (5-10 с)
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: MindBox_webapp
              key: DB_HOST
        ports:
        - containerPort:  80
          name:  MindBox_webapp
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always

test: